#!/bin/bash
# Operabase pre-commit hook
# Runs quality gates before each commit
# Generated by: npx operabase init

npx operabase gates --stage pre_commit

exit_code=$?
if [ $exit_code -ne 0 ]; then
  echo ""
  echo "❌ Pre-commit gates FAILED. Fix the issues above before committing."
  echo "   Run 'npx operabase gates --stage pre_commit' to see details."
  exit $exit_code
fi
