#!/bin/bash
# Operabase pre-push hook
# Runs full quality gates before push
# Generated by: npx operabase init

npx operabase gates --stage pre_push

exit_code=$?
if [ $exit_code -ne 0 ]; then
  echo ""
  echo "❌ Pre-push gates FAILED. Fix the issues above before pushing."
  echo "   Run 'npx operabase gates --stage pre_push' to see details."
  exit $exit_code
fi
